# Custom Relaxed IK config for Panda FR3
urdf: panda_drake.urdf
link_radius: 0.05 
base_links:
  - world
ee_links:
  - rubber_pad
starting_config: [0.0, -0.785, 0.0, -2.356, 0.0, 2.85, -0.785]  # Custom initial pose
obstacles:
